name: Test model solution with GAMS

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install GAMS
        run: |
          cd ~
          wget -nv https://d37drm4t2jghv5.cloudfront.net/distributions/29.1.0/linux/linux_x64_64_sfx.exe
          chmod 755 linux_x64_64_sfx.exe
          ./linux_x64_64_sfx.exe
          echo "~/gams29.1_linux_x64_64_sfx" >> $GITHUB_PATH
      - name: Run GAMS
        run: |
          gams PartialEq.gms
          cat PartialEq.lst
          if [-e PartialEq_sol.gms]; then
            gams PartialEq_sol.gms
            cat PartialEq_sol.lst
          fi
          grep -A 2 -B 2 --color "\\$[0-9]" *.lst || true
          grep -c "\\$[0-9]" *.lst || true
      - name: Archive results
        uses: actions/upload-artifact@v2
        with:
          name: lst-files
          path: *
